import Head from "next/head";
import Image from "next/image";
import banner1 from "../public/banner1.jpg";
import banner2 from "../public/banner2.jpg";
import banner3 from "../public/banner3.jpg";
import banner4 from "../public/banner4.jpg";
import banner5 from "../public/banner5.jpg";
import React from "react";
import useEmblaCarousel from "embla-carousel-react";
import Autoplay from "embla-carousel-autoplay";

export default function Home() {
  const autoplayOptions = {
    delay: 2000,
    rootNode: (emblaRoot) => emblaRoot.parentElement,
  };
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true }, [
    Autoplay(autoplayOptions),
  ]);
  return (
    <>
      <Head>
        <title>TrendVogue</title>
        <meta ngithubame="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* Slider */}
        <div>
          <div className="embla" ref={emblaRef}>
            <div className="embla__container">
              <div className="embla__slide">
                <Image src={banner1} alt="Banner" />
              </div>
              <div className="embla__slide">
                <Image src={banner4} alt="Banner" />
              </div>
              <div className="embla__slide">
                <Image src={banner2} alt="Banner" />
              </div>
              <div className="embla__slide">
                <Image src={banner3} alt="Banner" />
              </div>
              <div className="embla__slide">
                <Image src={banner5} alt="Banner" />
              </div>
            </div>
          </div>
        </div>

        {/* Boxes */}
        <div className="p-2 flex flex-wrap justify-center">
          <div className="w-40 md:w-72 mx-2 text-center">
            <Image
              src="https://images.bewakoof.com/uploads/grid/app/revamp-thumbnails-new-arrivals-1687584021.jpg"
              layout="responsive"
              width={1200}
              height={500}
              className="rounded-md"
              alt="Box 1"
            />
            <p>New Arrivals</p>
          </div>
          <div className="w-40 md:w-72 mx-2 text-center">
            <Image
              src="https://images.bewakoof.com/uploads/grid/app/revamp-thumbnails-bestsellers-1687584022.jpg"
              layout="responsive"
              width={1200}
              height={500}
              className="rounded-md"
              alt="Box 2"
            />
            <p>Best Sellers</p>
          </div>
          <div className="w-40 md:w-72 mx-2 text-center">
            <Image
              src="https://images.bewakoof.com/uploads/grid/app/revamp-thumbnails-collab-1687584023.jpg"
              layout="responsive"
              width={1200}
              height={500}
              className="rounded-md"
              alt="Box 3"
            />
            <p>Official Merch</p>
          </div>
          <div className="w-40 md:w-72 mx-2 text-center">
            <Image
              src="https://images.bewakoof.com/uploads/grid/app/revamp-thumbnails-last-sizes-left-1687584024.jpg"
              layout="responsive"
              width={1200}
              height={500}
              className="rounded-md"
              alt="Box 4"
            />
            <p>Coupon Offers</p>
          </div>
        </div>
      </main>
    </>
  );
}
